### PR TITLE
Fix/text cutoff when scaling

### PR DESCRIPTION
**Pull request by jcdhlzq**
Fix Text cut off issues when adjusting text size and font weight in system settings.

## Summary:

This pr fixed the problem that can be reproduced with the [snack](https://snack.expo.dev/fl5DSrLBJ) on Xiaomi devices with MIUI13 and MIUI14. The problem is shown as the image below: the number "999" is cut off and only "99" is rendered.
text-cutoff-when-scaling-miui14

The problem is produced with setting font scaling in system settings like the image below shows.

settings 

This text cut off case can be avoided by setting [`allowFontScaling`](https://reactnative.cn/docs/text#allowfontscaling) to false. But this pr can make it no matter what value `allowFontScaling` is set.

The root cause of this case, according to MIUI developers, is that Misans typeface, as a variable font which will adjust the weight of different font axes with different font size, gets different widths when Text is measured and drawn for a bug in the framework of MIUI rom. They will fix this bug in next version while this pr fixed it in old versions.

## Changelog:

[ANDROID][FIXED]-Fix Text cut off issues when adjusting text size and font weight in system settings.

## Test Plan:

The effect after fixed is shown in the image below.

fixed

### CODE REVIEW

**Comment by jcdhlzq** [comment]
This PR fixed npe in #39581 which has been reverted.

**Comment by jcdhlzq** [comment]
Hi, @NickGerleman 

Could you help to review this PR?

**Comment by andyjxli** [comment]
@jcdhlzq hi, I have the same problem as you, but I set allowFontScaling to false, and still could not display the numbers completely. what should I do? 
`<Text style={styles.price} allowFontScaling={false}>103</Text>`
`const price: TextStyle = {
    color: '#FF2442',
    fontSize: 32,
    fontWeight: FontWeight.medium,
    lineHeight: LineHeight.DisplayLabel,
    fontFamily: '',
    marginLeft: 2,
  };`
image

**Comment by yuzhiqiang1993** [comment]
所以这个问题还没有被解决吗

**Pull request closed without merging**
